name       : python-josepy
version    : 1.4.0
release    : 5
source     :
    - https://github.com/certbot/josepy/archive/v1.4.0.tar.gz : 748431e4710135e50d5dcc67508ab5cdfeed8240c29560cd14f5b7f8d98f9e4d
license    : Apache-2.0
component  : programming.python
summary    : JOSE protocol implementation in Python using cryptography
description: |
    Python implementation of the standards developed by IETF Javascript Object Signing and Encryption (JOSE).
builddeps  :
    - python-mock
    - python-openssl
    - python-pytest
rundeps    :
    - python-openssl
setup      : |
    %patch -p1 < $pkgfiles/0000-ignore-missing-linters.patch
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
