name       : python-josepy
version    : 1.0.1
release    : 1
source     :
    - https://pypi.io/packages/source/j/josepy/josepy-1.0.1.tar.gz : 9f48b88ca37f0244238b1cc77723989f7c54f7b90b2eee6294390bacfe870acc
license    : Apache-2.0
component  : programming.python
summary    : JOSE protocol implementation in Python using cryptography
description: |
    Python implementation of the standards developed by IETF Javascript Object
    Signing and Encryption (JOSE).
builddeps  :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
