name       : python-josepy
version    : 1.1.0
release    : 2
source     :
    - https://pypi.io/packages/source/j/josepy/josepy-1.1.0.tar.gz : fb5c62c77d26e04df29cb5ecd01b9ce69b6fcc9e521eb1ca193b7faa2afa7086
license    : Apache-2.0
component  : programming.python
summary    : JOSE protocol implementation in Python using cryptography
description: |
    Python implementation of the standards developed by IETF Javascript Object Signing and Encryption (JOSE).
builddeps  :
    - python-mock
    - python-openssl
    - python-pytest
rundeps    :
    - python-openssl
setup      : |
    %patch -p1 < $pkgfiles/0000-ignore-missing-linters.patch
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
